version: '3.8'

services:
  postgres:
    image: postgres:alpine3.16
    container_name: marketplace-db
    restart: always
    environment:
      POSTGRES_DB: marketplacedb
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace_network

volumes:
  postgres_data:

networks:
  marketplace_network:
    driver: bridge